apiVersion: v1
data:
  default.conf: |+
    server {
        listen       80;
        server_name  localhost;

        location / {
            proxy_pass https://pd-swarm.nyc3.digitaloceanspaces.com/;
            proxy_hide_header      Strict-Transport-Security;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

kind: ConfigMap
metadata:
  name: config-nginx
